### ISSUE TITLE
Build a basic readme file generator 

### ISSUE THREAD

**Issue by prajwalraju** [prajwalraju/RepoReady#4]

**Comment by aikooo7** [comment]
Will be doing it.

Any structure idea you have in mind? @prajwalraju

**Comment by prajwalraju** [comment]
Hey thank you for your help, You can add prompts for the user to enter the fields, if entered empty skip the section in the readme file.

You can use the below structure

- Project's Title
- Project Description
- Features
- Installation

**Comment by aikooo7** [comment]
Thanks for the answer @prajwalraju , last question, you want me to do it in the main.go file or in a other file like readme_generator.go?

If so, say the name please.

**Comment by prajwalraju** [comment]
You can add it in the utils folder, please use promptui for taking in prompts from the user

**Comment by aikooo7** [comment]
@prajwalraju Ignore the last comment I send, I decided my way to do it.

**Comment by prajwalraju** [comment]
Hey, thank you for the PR sorry for not providing the project structure before. I have added a few comments to the PR please fix them before merging.

**Comment by prajwalraju** [comment]
This is closed with #12
